inherit_gem:
  decidim-dev: rubocop-decidim.yml

# Override inherited require statements to avoid loading extensions
# that may not be available in all environments
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-faker

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*.rb'
    -  decidim-signature_collection/spec/decidim_dummy_app/**/*

Layout/SpaceAroundOperators:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false
