inherit_gem:
  decidim-dev: rubocop-decidim.yml

Layout/SpaceAroundOperators:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false
