default: &default
  # Database configuration
  DB_PORT: "5432"
  DB_POOL: <%= ENV.fetch("RAILS_MAX_THREADS") { "5" } %>
  DB_HOST: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  # Mailer configuration
  SMTP_ADDRESS: "smtp email address"
  SMTP_DOMAIN: "smtp email domain"
  SMTP_PORT: "587"
  SMTP_USERNAME: "smtp email username"
  SMTP_PASSWORD: "smtp email password"
  # GeoCoder configuration (developer.here.com)
  GEOCODER_LOOKUP_APP_ID: "here_app_id"
  GEOCODER_LOOKUP_APP_CODE: "here_app_code"

development:
  <<: *default
  DB_DATABASE: "sge_plus_development"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"

test:
  <<: *default
  TEST_DB_DATABASE: "sge_plus_test"
  TEST_DB_USERNAME: "postgres"
  TEST_DB_PASSWORD: "postgres"

integration:
  <<: *default
  # secrets
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>

staging:
  <<: *default

production:
  <<: *default
